config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  root  'users#index'

  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end


  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          resources :comments
        end
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, class_name: 'Post', foreign_key: :post_id

  validates_presence_of :text, presence: true, length: { minimum: 3, maximum: 250 }
  after_create :increment_comments_counter
  after_destroy :decrement_comments_counter

  def increment_comments_counter
    post.increment!(:comments_counter)
  end

  def decrement_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      skip_before_action :verify_authenticity_token, only: [:create]

      def index
        @post = Post.find(params[:post_id])
        respond_to do |format|
          format.json { render json: @post.comments }
        end
      end

      def create
        @user = User.find(params[:user_id])
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(comment_params)
        @comment.author = @user

        if @comment.save
          respond_to do |format|
            format.json { render json: @comment, status: :created }
          end
        else
          respond_to do |format|
            format.json { render json: @comment.errors, status: :unprocessable_entity }
          end
        end
      end

      def comment_params
        params.require(:comment).permit(:text)
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = @user

    if @comment.save
      redirect_to user_posts_url, notice: 'Comment successfully created.'
    else
      render :new, status: :unprocessable_entity
      flash[:alert] = 'There was an error saving this comment.'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to user_posts_path(current_user), notice: 'Post was successfully deleted.'
    else
      redirect_to user_posts_path(current_user), alert: 'Failed to delete the post.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/views/comments/new.html.erb
<h1 class="text-center font-bold text-2xl">Add a comment</h1>

<%= form_with model: @comment, url: user_post_comments_path(@user, @post), method: :post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <%form.object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <%end %>
  <div>
    <%= form.label :text, class: 'block mb-2 text-md font-medium' %>
    <%= form.text_area :text, placeholder: 'Place your comments here... ' , class: "block p-2.5 w-full text-sm text-gray-900 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>
  <button type="button" class="focus:outline-none text-white bg-green-700
  hover:bg-green-800 cursor:pointer focus:ring-4 focus:ring-green-300 font-medium rounded-lg
  text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700
  dark:focus:ring-green-800 mt-4">
    <%= form.submit %>
  </button>
<% end %>