config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  root  'users#index'

  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end


  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          resources :comments
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, through: :posts
  has_many :likes, through: :posts

  validates :name, presence: true, length: { minimum: 3 }
  validates :posts_counter, numericality: { integer: true, greater_than_or_equal_to: 0 }
  validates :bio, presence: true, length: { minimum: 5, maximum: 500 }

  before_create :set_default_photo
  before_create :set_default_role

  ROLES = %i[admin user].freeze

  def admin?
    role == 'admin'
  end

  def set_default_photo
    self.photo ||= "https://randomuser.me/api/portraits/men/#{rand(1..100)}.jpg"
  end

  def set_default_role
    self.role ||= 'user'
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      def index
        @user = User.all
        respond_to do |format|
          format.json { render json: @user }
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, flash[:alert] = 'Could not find user'
  end
end

app/views/users/index.html.erb
<div class="w-full h-full flex-col ">
  <% @user.each do |user| %>
    <div class="card">
      <div class="user-card flex flex-col gap-2 mt-4 items-center
       bg-white border border-gray-200 rounded-lg shadow md:flex-row
       md:w-auto hover:bg-gray-100 dark:border-gray-700">
          <img class="object-cover h-full w-full rounded-t-lg h-96 md:h-auto md:w-48
       md:rounded-none md:rounded-l-lg" src="<%= user.photo %>" alt="user image">
        <div class="flex flex-col justify-between p-4 leading-normal w-full h-40">
          <h5 class="mb-2 text-4xl font-bold tracking-tight"><%= user.name %></h5>
          <p class="mb-3 text-right font-normal">number of posts: <%= user.posts_counter %></p>
        </div>
      </div>
      <% if user.posts.empty? %>
        <button class="text-gray-900 bg-white hover:bg-gray-100
         border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
         font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
         dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
         dark:hover:bg-gray-200 mb-2 mt-4" type="button">
          <%= link_to 'Add a post', new_user_post_path(user.id) %>
        </button>
      <% else %>
        <button id="user-post" class="text-gray-900 bg-white mt-4 hover:bg-gray-100
         border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
         font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
         dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
         dark:hover:bg-gray-200 mb-2" type="button">
          <%= link_to 'See posts', user_path(user.id) %>
        </button>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="w-full h-full">
  <div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row
  md:w-auto hover:bg-gray-100 dark:border-gray-700">
    <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="<%= @user.photo %>" alt="user image">
    <div class="flex flex-col justify-between p-4 leading-normal w-full h-40">
      <h5 class="mb-2 text-4xl font-bold tracking-tight"><%= @user.name %></h5>
      <p class="mb-3 text-right font-normal">number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class="flex flex-col shadow-2xl p-4 h-50 mt-4 border-gray-100">
    <h3 class="text-2xl">Bio</h3>
    <p class="font-medium pt-2"><%= @user.bio %></p>
  </div>
  <% @user.recent_posts.each_with_index do |post, index| %>
      <div class="flex flex-col shadow-2xl mt-4 px-5 pb-3">
        <h5 class="mb-2 font-bold">Post # <%= index + 1 %></h5>
        <p class="mb-3 font-normal text-gray-700"><%= post.title %></p>
        <div class="flex justify-end gap-2">
          <span>Comments: <%= post.comments_counter %></span>
          <span>Likes: <%= post.likes_counter %></span>
        </div>
      </div>
  <% end %>
  <div class="flex items-center justify-center mt-5 gap-2">
    <% if @post.empty? %>
      <button type="button" class="text-gray-900 bg-white hover:bg-gray-100
       border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
       font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
       dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
       dark:hover:bg-gray-200 mb-2">
        <%= link_to 'Add a post', new_user_post_path(@user.id) %>
      </button>
    <% else %>
      <button class="text-gray-900 bg-white hover:bg-gray-100
         border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
         font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
         dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
         dark:hover:bg-gray-200 mb-2" type="button">
        <%= link_to 'See all posts', user_posts_path(@user.id) %>
      </button>
    <% end %>
  </div>
</div>