config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  root  'users#index'

  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end


  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          resources :comments
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, dependent: :destroy
  has_many :likes

  validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :text, presence: true, length: { minimum: 5, maximum: 1000 }
  validates :likes_counter, numericality: { integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { integer: true, greater_than_or_equal_to: 0 }

  after_save :increment_posts_counter
  after_destroy :decrement_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_posts_counter
    author.increment!(:posts_counter)
  end

  def decrement_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        @user = User.includes(:posts).find(params[:user_id])
        @post = Post.includes(:author, :comments, :likes).where(author_id: @user.id)

        respond_to do |format|
          format.json { render json: @post }
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:comments).find(params[:user_id])
    @user = User.includes(:posts).find(params[:user_id])
    @post = Post.includes(:author, :comments, :likes).where(author_id: @user.id)
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to user_path(current_user.id), notice: 'Post was successfully created'
    else
      flash[:alert] = 'There was an error saving this post.'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.comments.destroy_all
    @post.likes.destroy_all
    if @post.destroy
      redirect_to user_posts_path(current_user), notice: 'Post was successfully deleted.'
    else
      redirect_to user_posts_path(current_user), alert: 'Failed to delete the post.'
    end
  end

  def new
    @post = Post.new
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :author_id)
  end
end

app/views/posts/index.html.erb
<div class="w-full h-full">
    <div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row
      md:w-auto hover:bg-gray-100 dark:border-gray-700 ">
      <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="<%= @user.photo %>" alt="user image">
      <div class="flex flex-col justify-between p-4 leading-normal w-full h-40">
        <h5 class="mb-2 text-4xl font-bold tracking-tight"><%= @user.name %></h5>
        <p class="mb-3 text-right font-normal">number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
    <% @user.posts.each do |post| %>
      <div class="shadow-2xl">
        <div id="post-card" class="flex flex-col mt-4 px-5 pb-3">
          <h5 class="mb-2 font-bold"><%= post.title %></h5>
          <p class="mb-3 font-normal text-gray-700"><%= post.text %></p>
          <div class="flex justify-end gap-2">
            <span>Comments: <%= post.comments_counter %></span>
            <span>Likes: <%= post.likes_counter %></span>
          </div>
        </div>
        <div class="mt-4 px-5 pb-3">
          <ul class="">
            <% post.recent_comments.each do |comment| %>
              <li class="list-none"><%= comment.author.name %> : <%= comment.text %></li>
            <% end %>
          </ul>
        </div>
        <div class="flex items-center justify-center gap-2 mb-4">
        <button class="text-gray-900 bg-white mt-4 hover:bg-gray-100
         border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
         font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
         dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
         dark:hover:bg-gray-200 mb-2" type="button">
        <%= link_to 'Read more', user_post_path(user_id: @user.id, id: post.id) %>
        </button>
          <% if can? :destroy, post %>
            <%= button_to 'Delete', user_post_path(@user.id, post.id), method: :delete, class: "text-gray-900 bg-white mt-4 hover:bg-gray-100
         border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
         font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
         dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
         dark:hover:bg-gray-200 mb-2", type: "button" %>
          <% end %>
            <button class="text-gray-900 bg-white mt-4 hover:bg-gray-100
         border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
         font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
         dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
         dark:hover:bg-gray-200 mb-2" type="submit">
              <%= form_with url: user_post_likes_path(@user.id, post.id), method: :post, remote: true do |form| %>
                <%= form.hidden_field :author_id, value: current_user.id %>
                <%= form.hidden_field :post_id, value: post.id %>
                <%= form.submit "Like" %>
              <% end %>
            </button>
            <button class="text-gray-900 bg-white mt-4 hover:bg-gray-100
         border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
         font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
         dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
         dark:hover:bg-gray-200 mb-2" type="button">
              <%= link_to 'Add a comment', new_user_post_comment_path(user_id: current_user, post_id: post.id) %>
            </button>
       </div>
      <% end %>
    </div>
  </div>
  <div class="flex items-center justify-center mt-5">
    <div class="flex">
      <a href="#" class="flex items-center justify-center px-3 h-8 mr-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 text-gray-900 hover:bg-gray-200 hover:text-black">
        <svg class="w-3.5 h-3.5 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5H1m0 0 4 4M1 5l4-4"/>
        </svg>
        Previous
      </a>
      <a href="#" class="flex items-center justify-center px-3 h-8 mr-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 text-gray-900 hover:bg-gray-200 hover:text-black">
        Next
        <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
      </a>
    </div>
</div>

app/views/posts/new.html.erb
<h1 class="text-center text-4xl">Create a Post</h1>

<%= form_with model: @post,url: user_posts_path(current_user), method: :post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <%form.object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <%end %>
  <div class="mt-4">
    <%= form.label :title, class: 'block mb-2 text-sm font-medium'%>
    <%= form.text_field :title , placeholder: 'Title', class: 'block p-2.5 w-full text-sm text-black
     rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500
     dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500'%>
  </div>
  <div class="mt-4">
    <%= form.label :text,class: 'block mb-2 text-sm font-medium'%>
    <%= form.text_area :text, placeholder: 'Your text here...', class: 'block p-2.5 w-full
    text-sm text-black rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500
      dark:border-gray-600 dark:placeholder-gray-400 white:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500'%>
  </div>
  <button class="text-gray-900 bg-white mt-4 hover:bg-gray-100
       border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100
       font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center
       dark:focus:ring-gray-800 dark:bg-white dark:border-gray-700 dark:text-gray-900
       dark:hover:bg-gray-200 mb-2" type="button">
    <%= form.submit %>
  </button>
<% end %>

app/views/posts/show.html.erb
<div class="h-full w-full shadow-2xl flex flex-col gap-2">
  <div class="flex justify-between p-2">
    <h3 class="font-medium"><%= @post.title %> by <%= @post.author.name %></h3>
    <div>
      <span>Comments: <%= @post.comments_counter %></span>
      <span>Likes: <%= @post.likes_counter %></span>
    </div>
  </div>
  <div class="flex flex-col p-2">
    <p>
      <%= @post.text %>
    </p>
    </div>
    <div class="font-medium text-sm p-2">
      <% @post.comments.each do |comment| %>
        <div class="flex justify-between items-center mr-3">
        <p><%= comment.author.name %> : <%= comment.text %></p>
        <% if can? :destroy, comment %>
          <%= button_to 'Delete', user_post_comment_path(user_id: @user.id, post_id: @post.id, id: comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </div>
    <% end %>
    </div>
</div>